### ISSUE TITLE
gridGlue coupling is recomputed all the time instead of caching it

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#1007]
We could store the coupling and recompute it when load balancing has occurred. But no, we do it every time. Also, we sort the cell lists twice, and we clear the maps that weren't reused anyway. So potential for cleanup and optimization there.

FIC spends about 5% in what I eyeball as mostly the recomputation of the coupling (though *maybe* it's also MPI to some extent). But whyyy didn't we bother caching that?!

**Comment by ursg** [comment]
Fixed by #1012
