### ISSUE TITLE
Multiple populations in Vlasiator

### ISSUE THREAD

**Issue by sandroos** [fmihpc/vlasiator#113]
I'll open a new issue for a couple specific things.

cell parameters
- currently the is only number density (rho, 1/m3)
- we could really use the mass and charge densities instead (as kg/m3 and C/m3)
- this affects multipop solver and a few places in the code
  - moment calculations (Vlasov solver, analysis tools)
  - acceleration transformation / Lorentz force (Vlasov solver)
  - Hall term (field solver)

Vlasov boundary conditions
- these are now based on cell status, but boundary conditions may be different for different species
  - distributions at least are different
- sysBoundaryFlag should be per particle population

Are there any other places I forgot where protons are assumed in the code?

**Comment by ursg** [comment]
This is now implemented as of version 4.0
