### ISSUE TITLE
Investigate space-filling curves

### ISSUE THREAD

**Issue by ohannuks** [fmihpc/vlasiator#119]
Currently we do sorting in velocity space for blocks before acceleration/translation to reduce cache misses.

One of the known ways to cache misses is the space-filling curves. This is implemented in most modern mesh libraries ( http://www.sci.utah.edu/publications/Dub2014a/Dubey_JPDC2014.pdf ) and there are loads of different algorithms for implementing it: Hilbert w/ fast sorting, Morton, Piano Hilbert at least seem to be widely used.

Whether the space filling curves in velocity space help with performance in Vlasiator is still an open question and it should be investigated. The first step would be to use performance analysis tools (Papi, CrayPat, ..) to analyze cache performance and determine whether we have any space for improvement.

If we need to improve the performance, the next step would be to look for different space filling curves and choose the one that fits our needs (algorithm should be fast and it should work with unstructured meshes). We could also look for existing implementations.

**Comment by ursg** [comment]
Especially with AMR on the horizon, the block numbering scheme will anyway not be amenable to this sort of curves. So let's leave this on the "good idea, but no" - pile.

**Comment by iljah** [comment]
Which blocks are you referring to?

**Comment by iljah** [comment]
Actually thinking about this more, and assuming this is about velocity blocks of one cell, I vaguely remember that I tried this back when @sandroos was leading code development. Ordering velocity blocks in vector based on SFC ordering instead of regular didn't help.

**Comment by galfthan** [comment]
yes, unfortunately vlasov solvers are not memory bandwidth bound

**Comment by tkoskela** [comment]
Out of curiosity mostly, if we are not BW bound, then what are we bound by?

**Comment by iljah** [comment]
Yeah on current hardware shouldn't there be like > 1000 flop/byte to be CPU bound?

**Comment by galfthan** [comment]
Well, if we had a roofline model expert then one could analyze where the solvers are ;) Probably not too good looking there I would assume. There are for sure things that could be improved in the throughput of the solvers, avoiding stalls for various resources etc. There are also a lot of flops.

**Comment by tkoskela** [comment]
Not quite, at around 10 flops per byte you can be compute bound. But that is still 80 flops per double. It would be interesting to do roofline analysis for the solvers, I was just wondering if you knew already where they are :)
