### ISSUE TITLE
vlsvdiff not working on hornet

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#134]
Program terminated with signal 4, Illegal instruction.
#0  0x0000000000433df8 in muxml::MuXML::read(std::istream&, muxml::XMLNode*, int const&, char const&) ()

(gdb) backtrace
#0  0x0000000000433df8 in muxml::MuXML::read(std::istream&, muxml::XMLNode*, int const&, char const&) ()
#1  0x000000000042ed01 in vlsv::Reader::open(std::string const&) ()
#2  0x000000000042db1e in checkVersion(std::string const&) ()
#3  0x000000000040747d in process2Files(std::string, std::string, char const*, unsigned int, bool, unsigned int) ()
#4  0x0000000000400984 in main ()

Is this related to the new footer things?

**Comment by ursg** [comment]
As we no longer have access to Hornet/Hazelhen, this problem is no longer relevant.
