### ISSUE TITLE
Dynamic sparse adjustment stuff does not work for multipop plasmas

### ISSUE THREAD

**Issue by sandroos** [fmihpc/vlasiator#136]
This update heavily assumes that there is only one particle species. The related parameters (sparseDynamicMinValue1 etc) need to be defined for each particle species and thus cannot reside in parameters.h file.

**Comment by ursg** [comment]
This was, indeed, implemented in f550571aefc6f0c96fbb2877290a84f0d1ed0ac6, and has been tested in global helium and oxygen runs.
