### ISSUE TITLE
System boundary layers

### ISSUE THREAD

**Issue by sandroos** [fmihpc/vlasiator#145]
Is there some specific reason why the outermost spatial cells have `sysBoundaryLayer==2` ? 

![visit0000](https://cloud.githubusercontent.com/assets/7443488/7564814/facfa71c-f7f2-11e4-9f98-c1e56a311819.png)

If the numbering was different, it would be possible to loop over spatial cells and `sysBoundaryLayer==2` would indicate that this is the cell just next to system boundary condition cells, but now that condition grabs the outermost cells too.

Imo it would be better if the numbering was (0,1,2,3,something) instead of the current (2,1,2,3,0). At least I could more easily implement boundary conditions for the Poisson solvers using those values..

**Comment by ykempf** [comment]
We've been living with the positive-only layer system for a long time without issues so closing for now.
