### ISSUE TITLE
Suspected potential CFL break in the field solver subcycling

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#163]
Following the crash of BCH at 1328 s and investigations as well as flowdock discussions I open an issue about that. The suspicion is that with 50 substeps in critical places like behind FTEs where a few cells get nasty every now and then, the field solver could exceed CFL in the subcycling process and blow up eventually.

I paste below the wrapup I posted on flowdock too with my suggested solution:

so in shorter:
1. save before subcycle loop what is needed initially (E,B I think, rho and V stay put, derivatives can be recalculated), into the *_DT2 fields (I fear there's some communication needed there too but well...)
2. do the subcycle loop and at each iteration each cell in each process checks whether it would exceed CFL conditions
3. after the loop finishes do a global reduce, if anyone anywhere exceeded, then compute how many more substeps are needed, rewind using the stored values and redo the for loop with more substeps

after that make sure that the global timestep gets notified and that the actually used number of subcycles is posted to the logfile (e.g. add a warning that the previous was displayed as n but became n+10)

actually one more thought: we could/should maybe have a form of static maxdt to record peaks during the 50 substeps in order to change the global dt w.r.t the shortest during all subcycles, not the last one only

**Comment by galfthan** [comment]
This is fixed, is it not?

**Comment by ursg** [comment]
It is fixed, and it has been for a long time.
