### ISSUE TITLE
Second layer cells on outflow boundaries have bad moments / veloctiy space contents.

### ISSUE THREAD

**Issue by ohannuks** [fmihpc/vlasiator#2]
I ran the Shocktest project with the full3dslice branch with outflow set on the x+. The third order solution produced a huge spike at the outflow boundary, giving the last cell a rho value of 7.46e6. The second last cell had a value of 2.75e6.

The second order solution didn't produce the same spike.

![shocktest](https://f.cloud.github.com/assets/6065150/2108378/6299a0e2-8fde-11e3-9ebf-8f1d78ddcbf4.png)

**Comment by ykempf** [comment]
This has been fixed.
