### ISSUE TITLE
electron pressure term broken in vlasov solver due to vlasiator 3 merge

### ISSUE THREAD

**Issue by galfthan** [fmihpc/vlasiator#226]
In multipop a lot of vlasov solver code moved from hpp files to cpp files. It seems that when merging electron pressure branch to Vlasiator 3 we lost the electron pressure changes in cpu_acc_transform.hpp, since the code was now in cpu_acc_transform.cpp. 

We should in general look at the codes in vlasiator 2 hpp files and vlasiator 3 cpp files to see if we can spot any other changes that are MIA.

**Comment by markusbattarbee** [comment]
Electron pressure term is currently working.
