### ISSUE TITLE
Magnetosphere distribution picker spatial/velocity sampling asymmetry

### ISSUE THREAD

**Issue by markusbattarbee** [fmihpc/vlasiator#249]
In https://github.com/fmihpc/vlasiator/blob/master/projects/Magnetosphere/Magnetosphere.cpp#L165
if only one of nSpaceSamples and nVelocitySamples is different from 1, the picker defaults that one to 1. Using a logical OR for this line is not enough, as in that case for the domain where only 1 sample is required, it would be offset to the side.

**Comment by ykempf** [comment]
I pushed this one out now. It could do with some testing to make sure there is no problem, of course.

Question to @markusbattarbee or @ursg, should I copy this over to all projects with these sampling cfg parameters?

**Comment by ykempf** [comment]
I could also make sure #256 is fixed at the same time.
