### ISSUE TITLE
sysBoundaryLayerNew does not seem to be used and has hard-coded "magic" values

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#254]
https://github.com/ursg/vlasiator/blob/improve_outflow_boundary/sysboundary/sysboundary.cpp#L338
This part of the code needs to be reviewed, it does not seem to be used (yet?) and it has hard-coded magic values (`Real x_bndr = 900.0;   Real y_bndr = 700.0;`) which look highly suspicious to me.

**Comment by markusbattarbee** [comment]
This was cleaned up and removed for Vlasiator-4.0.
