### ISSUE TITLE
Enable 1 to inf nVelocitySamples and nSpaceSamples in all projects

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#256]
At least Flowthrough breaks with 1 velocity sample. This should be made consistent across projects.

**Comment by ykempf** [comment]
Note that Alfven uses a global vSpaceSamples whereas e.g. Magnetosphere has a population-specific one. Which one do we prefer? Or do we leave it inconsistent for now?

**Comment by markusbattarbee** [comment]
Nice find - I see no reason to leave it unfixed.

**Comment by ykempf** [comment]
I'll first port the general version allowing 1 to many, and in a second phase check whether I make nSpaceSamples population-specific or not.

**Comment by ykempf** [comment]
So I did see your suggestion @markusbattarbee to put this in a wrapper function, which I like a lot as it will save me a whole lot of copy-pasting, but I don't see it here. Did you remove the comment? I'll start with that anyway, and be most likely done by the time you have a chance to comment back, but I think it is very sensible to have one function instead of 15ish identical implementations.

**Comment by markusbattarbee** [comment]
The response about the wrapper was made to the actual commit :)
