### ISSUE TITLE
Upwinding is done with the whistler speed, it shouldn't

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#275]
According to a paper by Tóth et al, upwinding can be done with the magnetosonic speed only, putting a factor 0 in front of the whistler speed in the sum.

Extensive testing in summer 2016 based on test_fp and Flowthrough showed an instability developing chequerboards in the field solver when vMS + vW is used in upwinding.

The suggested improvement is to use only the magnetosonic speed for upwinding and vMS + vW for the determination of dt. The Hall and Hall drift speeds could be added but they are rather minor in current production simulations.

TODO:
- [x] Test with Dispersion to see whether differences appear.

**Comment by galfthan** [comment]
Is this not done now and can be closeD?
