### ISSUE TITLE
Acceleration is also limited by vlasov CFL

### ISSUE THREAD

**Issue by galfthan** [fmihpc/vlasiator#28]
The timestep that is computed by acceleration is also limited by vlasov CFL. We should use that only for real space and have separate bounds for velocity space (max rotation between 18 20 deg, e.g.).

**Comment by ursg** [comment]
This has, of course, been fixed a long time ago (see ```updateAccelerationMaxdt()``` in vlasovsolver/cpu_acc_transform.cpp).
