### ISSUE TITLE
Field solver Hall term density interpolation

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#306]
The Hall term in the field solver (2nd spatial order) uses the normal density (RHO). It should rather use some interpolation to the corresponding edge.
I see two options I have to think through:
- Take the average of all four neighbours (easier?);
- Interpolate from each cell to the each edge using that cell's derivatives only.

**Comment by ykempf** [comment]
Looking into this I now notice that option 1, averaging the four neighbouring cells for each edge, will be extremely painful to code as there is 12 edges per cell to go through and 3 neighbours each time to retrieve correctly.

Option 2 would use only the local information. Since the densities are limited there wouldn't be too big problems, and it would still always check whether the result is below the minimum Hall density.

**Comment by galfthan** [comment]
I think the second option would be the more correct solution, and the preferred one even if a bit more complicated to code. Now you are not limiting rho in the correct sense, one should check it is not above/below rho in the 4 cells adjacent to the edge. Also, I assume the value of the edge will not be consistent but depend on which cell you are handling when (did not check in code).

**Comment by ykempf** [comment]
I did code option 2 now. Do you mean option 1 would be better? I believe this is nicer in the sense that it does similar things as other parts of the field solver, namely calculate values in the edges based on interpolation. The values for a given edge will be different for each adjacent cell indeed, that's as the upwinding does for the full E. Is that what you mean with inconsistency?

**Comment by galfthan** [comment]
I meant option 1, sorry.  

That is what I meant with consistent, that may not matter much though.  

The fact that the value is not properly limited seems to be more of a problem, it can be higher or lower than any of the 4 adjacent cells. The same may be true for other parts of the fieldsolver.  @sandroos may also want to give his opinion.

**Comment by ykempf** [comment]
OK so assuming we instead do the Option 1, as it would include free limiting, so to say. Do we find a place in the solver where the interpolated value is computed for the base edges of a cell and we fetch the NE/SE/NW neighbours in the Hall computation? I guess this is best?

I am not sure how much of a problem the lack of limitation is. 1) The minimum Hall rho is anyway checked against. 2) The derivatives are limited, so this won't easily create/overshoot extrema.

But I see that as soon as we again have some unstable crash we'll be scurrying to implement this if it is not yet done, so I can do an option 1 version for sure.

**Comment by galfthan** [comment]
This is the same issue we had in Leveque. The derivatives are limited in 1D, so when interpolating to face, the value is indeed limited. Here you are doing it in 2D, and in practice this can create overshoots. You can easily demonstrate this with pen and paper.

**Comment by ykempf** [comment]
...yes I did already in my head, no worries, you won me over. The conundrum is beginning, wait for my next posts in flowdock.

**Comment by sandroos** [comment]
Are we talking about the Hall electric field here? 
If yes, is proper upwinding a factor?

Option 1 does something to proper upwinding. Option 2 is probably the correct approach to take, cell derivatives already take neighboring values into account. But yes, 3D limiters are a pain, idk if anyone has solved that issue..

**Comment by ykempf** [comment]
Yes this is about the Hall field. As a reminder, my implementation of Hall E computes the edge-averaged value of Hall E in every edge of every cell and adds that correspondingly to the upwinding scheme. So probably here we are only looking for a sensible edge-rho to put, hence now the implementation of Option 1 in the end yesterday.

**Comment by ykempf** [comment]
Solved by #315.
