### ISSUE TITLE
Thread count in logfile incorrect on sisu

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#320]
When running e.g.
`export OMP_NUM_THREADS=6 ; aprun -n 4 -d $OMP_NUM_THREADS ./vlasiator --run_config Magnetosphere_small.cfg`
the logfile only reports 1 thread, which is incorrect.

**Comment by galfthan** [comment]
This is running on interactive nodes? Environment variables are not exported automatically. Try adding the following option to aprun:

`-e OMP_NUM_THREADS=${OMP_NUM_THREADS}`
