### ISSUE TITLE
Reduced memory consumption in translation

### ISSUE THREAD

**Issue by galfthan** [fmihpc/vlasiator#331]
At the moment translation has a separate target and source grid. One can improve on this by adopting the same approach that is used in acceleration.   
 * Sort data in pencils in space
 * Load source data of one pencil in temporary array
 * Map, and write back into original grid.

This will have the following improved features
 * Vlasiator uses much less memory 
   * The distribution function per species is always in memory only once
   * Less memory churn (allocations, deallocations), which may improve memory fragmentation 
 * Most likely better performance due to improved data locality

**Comment by markusbattarbee** [comment]
Before implementing this, we should consider how AMR will affect this. I suppose this is mostly implementable, but the pencil width should be the width of the largest applicable cell (or, for simplicity's sake, the largest cell width found in the simulation domain).

**Comment by ursg** [comment]
This issue is obsolete with the AMR solver implementation.
