### ISSUE TITLE
Fix IO on Marconi

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#332]
Initial testing shows that IO is very slow for small files but excellent for big files (order of 10 MB/s for bulk files, 10 GB/s for restarts).

One find is that collective IO seems to be as fast as single IO for small data. So for now a workaround by @sandroos will be tested while waiting for suggestions by the CINECA helpdesk. This seems not to depend on the MPI implementation.

**Comment by ursg** [comment]
We ran on marconi and it wasn't too great. But now that is long done.
