### ISSUE TITLE
Incorrect mass in ionosphere maxwellian?

### ISSUE THREAD

**Issue by iljah** [fmihpc/vlasiator#333]
Equation at https://github.com/fmihpc/vlasiator/blob/master/sysboundary/ionosphere.cpp#L736 is otherwise the same as eq 6 in https://en.wikipedia.org/wiki/Maxwell%E2%80%93Boltzmann_distribution but mass in front of exp seems wrong. On wiki it's m^-1.5 and to get correct total mass multiply by rho and m which would give rho m^-0.5 instead of m^1.5 currently in the code. Or did I miss something?

**Comment by ykempf** [comment]
https://github.com/fmihpc/vlasiator/blob/master/projects/Magnetosphere/Magnetosphere.cpp#L366

Same here and we've always got the right result out of it, so I'd say you're missing something here.

**Comment by iljah** [comment]
I thought something like this was used but haven't dug further: https://github.com/fmihpc/vlasiator/blob/master/projects/project.cpp#L629

**Comment by ykempf** [comment]
No this is for rescaling density in case of losses due to numerics. Not the same.

**Comment by iljah** [comment]
I found this gem, no idea if it's related, but is that really (entire/total/etc) population mass instead of mass of that species / proton mass? https://github.com/fmihpc/vlasiator/blob/master/vlasovsolver/cpu_moments.h#L65

Anyway I'll just run it and see what comes out with m^-0.5 and m^1.5...

**Comment by ykempf** [comment]
population is equivalent to species in this comment. So for Uranium massRatio would be 235.

**Comment by ursg** [comment]
On 31/05/17 12:17, Ilja wrote:
> I found this gem, no idea if it's related, but is that really
> (entire/total/etc) population mass instead of mass of that species /
> proton mass?

I'm not sure what the difference here would be. The terms "population"
and "species" are used somewhat interchangably in the code. So a
population could be "helium" or "proton", but not "background", "beam"
or anything like that.

So the massratio parameter given to the function determines what the
effective mass of that part of velocity space is, and thus it gets
summed up accordingly.

Cheers,
//Urs
