### ISSUE TITLE
Improve algorithms for fmin vdf threshold

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#360]
During the discussion for my 1D shock paper Rami suggested the following:

One of the things that could be somehow thought of is also making the threshold dependent on thermal velocity of the cell, e.g., fmin ~ 1/(vth^2+v^2)^a. It could be cumbersome, but this would allow one to retain those cells in the calculation, where the particles are suprathermal and carrying a lot of energy.

I suggest a more or less long term plan to consider and test such alternatives to the determination of the phase space density threshold. I can imagine that taking into account the thermal speed/temperature in addition to the density could be a good idea.

**Comment by markusbattarbee** [comment]
Moving discussion to #432
