### ISSUE TITLE
Update return values of mpiGrid.get_neighbors_of

### ISSUE THREAD

**Issue by tkoskela** [fmihpc/vlasiator#378]
Latest version of dccrg returns std::vector<std::pair<uint64_t,std::array<int,4>>> instead of std::vector<uint64_t> from get_neighbors_of and its variants. There are calls to it in grid.cpp, sysboundary.cpp and projects_common.h at least, those should be updated to be able to compile with latest dccrg.

**Comment by ykempf** [comment]
Note than when rolling this out, the default DCCRG version should then also be updated in the places where we are running.

**Comment by tkoskela** [comment]
Updated in pull request #380
