### ISSUE TITLE
Finalizing AMR  version (Vlasiator 5)

### ISSUE THREAD

**Issue by galfthan** [fmihpc/vlasiator#396]
**Initial implementation**
- [x] Finish field gridglue (sebastian,tuomas)
 * Fields are moved, verified in non-AMR case
- [x] io from fsgrid (bulk) (urs)
 * Enables removal of many glue functions
- [x] Max dt for fieldsolver computed on fsgrid (urs)
 * Verified for magentosphere test
- [x] Setup boundary flags directly  on fsgrid  (yann,tuomas)
 * Compute at same time as dccrg flags, get's rid of one glue, OR implement glue

**Cleaning & refactoring after initial implementation:**
- [x] Remove old coupling functions (tuomas)
- [x] Remove unused variables from spatial cell class (tuomas)
- [x] Remove coupling code from fsgrid (urs,tuomas?)
- [ ] Reorganize fsgrids in container? (urs?)
- [x] Re-implement Ehall datareducer https://github.com/fmihpc/vlasiator/blob/dev/datareduction/datareducer.cpp#L542

**Validation & verification:**
- [x] Analysis in (larger) flowthrough tests
- [x] Analysis in small Magnetosphere tests
- [x] Scalability on Sisu
- [x] Thread scalability
- [x] vlsvdiff including fsgrid variables

**For production**
- [x] Restart writing of fsgrid data
- [x] Restart reading of fsgrid data

**Bugs**
- [x] bvol derivatives are not averaged correctly (see #bug-bvolderivative-avg-in-glue in flowdock)
- [x] Diffs in translation algorithm with size >1 pencils
- [x] TBA

**Numerical improvements**
- [x] May need interpolation in regridding moments dccrg => fsgrid.
 * One option is to use same mapping as in vlasov solver
- [ ] Move to a tight coupling at fieldolver dt between fieldsover and VDF transformation. 
 * See slideset in vlasiator-dev at #fs-vdftransform-coupling 
 * Not needed for initial V5 release, additional improvement.

**Comment by ursg** [comment]
Given the state of the AMR runs, this can be considered done! Rejoice!
