### ISSUE TITLE
Dynamic vector type arrays in AMR vlasov solver

### ISSUE THREAD

**Issue by tkoskela** [fmihpc/vlasiator#415]
The size of the Vec - type arrays targetVecData and sourceVecData in trans_map_1d_amr 
 https://github.com/fmihpc/vlasiator/blob/792bd70114f87fe3ec39d61af32d95f6873fb570/vlasovsolver/cpu_trans_map_amr.cpp#L1103

and

https://github.com/fmihpc/vlasiator/blob/792bd70114f87fe3ec39d61af32d95f6873fb570/vlasovsolver/cpu_trans_map_amr.cpp#L1155

is not known at compile time, since it depends on the amount and size of pencils. This can lead to crashes, or worse. The vectorclass documentation says on page 16

> If you need an array of a size that is determined at runtime, then you will have a problem with alignment. Each vector needs to be stored at an address divisible by 16, 32 or 64 bytes, according to its size. The compiler can do this when defining a fixed-size array, as in the above example, but not necessarily with dynamic memory allocation. If you create an array of dynamic size by using new, malloc or an STL container, or any other method, then you may not get the proper alignment for vectors and the program will very likely crash when accessing a misaligned vector.

**Comment by ursg** [comment]
Would it be sufficient to use an [alignas](https://en.cppreference.com/w/cpp/language/alignas) statement to them? Or do we have to work with explicit aligned mallocs here?

**Comment by tkoskela** [comment]
How much are we limited by what vectorclass allows us to do here though? The documentation is quite strongly suggesting not to allocate dynamic size arrays. But it should be possible to allocate aligned memory during runtime. Can we do it somehow?

The other option is to re-write quite a bit of the code so that the vector data types are only used deeper in the call tree, where we are operating on single cells and not pencils. This might actually make the code a bit cleaner but will take some time.

**Comment by ursg** [comment]
In the particle pusher, where dynamically-sized std::vetcros containing these vectors were also causing obscure runtime crashes, I fixed it by using an explicit request for an aligned allocator:

https://github.com/fmihpc/vlasiator/blob/792bd70114f87fe3ec39d61af32d95f6873fb570/particles/particles.h#L44

**Comment by tkoskela** [comment]
What are the template parameters to aligned_allocator?

**Comment by ursg** [comment]
see here: https://github.com/fmihpc/vlasiator/blob/792bd70114f87fe3ec39d61af32d95f6873fb570/memoryallocation.h#L97-L99

**Comment by tkoskela** [comment]
PR to implement aligned_allocators is here https://github.com/fmihpc/vlasiator/pull/416
