### ISSUE TITLE
VLSV cannot write more than 2GB of data per process per write due to MPI limitations

### ISSUE THREAD

**Issue by ohannuks** [fmihpc/vlasiator#45]
There is an issue which came up when testing the bailout function on low memory, which causes the program to crash when writing a restart from time to time.

Assert error:
Assertion failed in file /notbackedup/tmp/ulib/mpt/nightly/6.0/091013/mpich2/src/mpi/datatype/type_size.c at line 102: size_x >= 0

The issue occurs more often when low on memory but it is probably not solely a memory-related issue. There have been test cases with one node, two processes and 10 threads. In the test cases velocity space resolution was increased (10³, 11³, 12³, ... 60³ velocity space resolution) and the same job was run, the results were that on the current master branch (DP, DPF) ( 443c07954144590fe2920f7dd1fc344f9ee4924b ) the run crashes with hyper threading set to 1 in the following runs (number gives the velocity space resolution):

28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 55, 56

The run did not crash between 45-54, despite higher memory consumption.

This bug occurs in writing out the velocity space: 
https://github.com/fmihpc/vlasiator/blob/443c07954144590fe2920f7dd1fc344f9ee4924b/iowrite.cpp#L169-L186

It has been also tested that the bug occurs when we use the old version of writing out the velocity space with the writeArray function instead of the addMultiwrite and endMultiwrite.

I've run a test version where I print out the memory consumption right before writing the velocity space and in the test runs between 45-54 the memory consumption was higher than in 28-44, even though it did not crash.

**Comment by ykempf** [comment]
I think this is not relevant any more, we have the VLSV buffering and we track memory to bail out before we fill memory.
