### ISSUE TITLE
fluxfunction update

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#463]
`fluxfunction` does not read the fg_* fields, that needs to be done at some point.

Possibly this could be ported to Python, too?

Not very urgent.

**Comment by ykempf** [comment]
There is also issues with recent versions of the vectorclass which have `Vec3Dd` and `Vec3Df` instead of `Vec3d` but lacking some of the functions so that a `#define Vec3d Vec3Dd` is not sufficient.

**Comment by ursg** [comment]
Since the fluxfunction tool tries to read fields using the readfields function of the particle pusher, this issue also points to that one's inability to deal with fsgrid fields.
(Also meaning that fixing particles/readfields.h to be able to handle fsgrid fields will fix both)

**Comment by markusbattarbee** [comment]
Fixed by #556
