### ISSUE TITLE
initial-grid writing should be striped too

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#509]
initial-grid is very slow writing in a 3D production run. I suspect it's not striped by default like restarts. We might want to include that to the initial-grid IO as it is also a big file.

**Comment by markusbattarbee** [comment]
Yep, write initial grid uses the bulk file writing subroutine. And that doesn't set striping.

Shouldn't we stripe bulk file writing as well? Especially now that our bulk files are like 20 gigs. E.g. on hawk, the latest EGI runs have a directory striping of 4, and likely use the default striping chunk size of 1 MB. We could surely adjust those to be a lot better.

**Comment by ykempf** [comment]
Sure, although I haven't seen any issues in writing performance of the bulks, it's the DROs that are somewhat inefficient. We could add the striping hint as part of a given file type's (bulk, etc) option. Opinions?

**Comment by markusbattarbee** [comment]
Fixed by #514
