### ISSUE TITLE
Write fsgrid stencil width to vlsv files

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#555]
This might be useful e.g. to read in when using fluxfunction.

**Comment by markusbattarbee** [comment]
Hm, what, does fsgrid write ghost cells for each domain as well? That would be quite wasteful IMO and pointless (except for perhaps some VisIt plotting things, and even then, I'd think it'd be worth reconsidering, as our FSgrid variable writes are quite large in the big simulations)

**Comment by ykempf** [comment]
No, we'd like the parameter as fluxfunction would go along the edge of non-sysboundary cells.

**Comment by ykempf** [comment]
But anyway for now @lkotipal will make `2` either a default user parameter or a parameter at the top of the file for now.

**Comment by markusbattarbee** [comment]
but that has nothing to do with the fsgrid stencil width? especially as to be able to exclude sysboundary cells, one needs to take the sysboundary width (2 MPIgrid refLvl 0 cells, where is this even defined?) and find the maximum refLevel and multiply to get the width in FSgrid cells.

**Comment by ykempf** [comment]
No AMR in 2D runs for fluxfunction, luckily. But indeed it's a different parameter, my bad. So @lkotipal go with 2 anyway, make it a parameter if you want or leave it as is.
