### ISSUE TITLE
Unrecognized boundary type

### ISSUE THREAD

**Issue by henry2004y** [fmihpc/vlasiator#564]
I happen to realize that if the user inputs a wrong BC type name, e.g. `MaxwellianWrong`, the code won't crash, because in boundary loop in `sysboundary.cpp` only contains `if` but not `else`. Maybe we can add an `MPI_ABORT` for the exceptions.

**Comment by markusbattarbee** [comment]
Good idea!

**Comment by ursg** [comment]
With #567 merged, this is done.
