### ISSUE TITLE
`Project::setupBeforeSetCell` not used?

### ISSUE THREAD

**Issue by henry2004y** [fmihpc/vlasiator#641]
`Project::setupBeforeSetCell` is being defined in the Project class and called in https://github.com/fmihpc/vlasiator/blob/b26df8f3e75f6d81c23e531849b4d16938794869/grid.cpp#L262

However it is not currently used in any projects. What is the usage of this method, and shall we keep it?

**Comment by ykempf** [comment]
We have used it, but I don't remember what for nor when it wasn't used any more. Is it used in eVlasiator? If yes, then we should keep it here too. If not and no one remembers when/what for we used it, I guess it can go.

**Comment by ykempf** [comment]
Right, it is used by the ElVentana project in eVlasiator, that will be merged eventually I believe thus we could as well keep it here even if it does nothing for now...
