### ISSUE TITLE
Conducting sphere boundary

### ISSUE THREAD

**Issue by henry2004y** [fmihpc/vlasiator#764]
The current implementation of the conducting sphere boundary does the following:

https://github.com/fmihpc/vlasiator/blob/a6321aa7707405857655c90cf1e034653fe85d9d/sysboundary/conductingsphere.cpp#L476-L699

#552

1. Averaging the magnetic field from the inner cells neighboring to each boundary cell.
2. Retaining the perturbed B components normal to the boundary's surface.
3. Setting the electric fields to zeros.

Based on the boundary conditions for a perfect conductor (Eqs. 2.6.14-17 from [here](https://phys.libretexts.org/Bookshelves/Electricity_and_Magnetism/Electromagnetics_and_Applications_(Staelin)/02%3A_Introduction_to_Electrodynamics/2.06%3A_Boundary_conditions_for_electromagnetic_fields)) and the fact that EM fields must be zero inside the conductor, it seems that the correct boundary setup would be

1. Setting the perturbed B normal components to zero.
2. Letting the perturbed B tangential components be continuous across the conducting boundary.
3. Setting the electric fields to zeros.

The expected results would look like 
![image](https://github.com/fmihpc/vlasiator/assets/20110816/a39d1ba6-5e17-408b-9859-01fa59620c40)

i.e., perturbed/induced B field cannot penetrate into the conducting sphere.

Current Vlasiator 2D test with the conducting sphere generates field lines that looks like
![conducting_bc_test_2d_2](https://github.com/fmihpc/vlasiator/assets/20110816/9ada1f5e-b3e0-480f-9790-9a33b89af949)

**Comment by ykempf** [comment]
Thank you again for finding and reporting this! We switched to a Neumann condition for perturbed magnetic field as per the recent merges to `dev`.
