### ISSUE TITLE
Handle restart IO in bailout command

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#794]
https://github.com/fmihpc/vlasiator/blob/dev/vlasiator.cpp#L421-L432
As of recently we bail out on non-cubic cells. This was merged carelessly, by yours truly, but the old error message is obsolete with a bailout message following.
But the second, more important point, is that bailout writes a restart unless disabled in the cfg for all bailouts by `bailout.write_:restart`, which in production is usually not the case. Up for discussion:
- Introduce an additional flag possibility for bailout calls to override the cfg setting and not write a restart? In this specific case it just litters the file system to write a restart for a failed initialisation setup?
- or: just abort here as we won't run nor restart with the non-cubic cells?

**Comment by markusbattarbee** [comment]
just abort here as we won't run nor restart with the non-cubic cells
