### ISSUE TITLE
Can vlsv2silo be fixed to convert velgrid vlsv files?

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#80]
I noticed that vlsv2silo cannot convert vlsv velgrids into silo. Is it easy to fix? I can also use an old vlsvextract to get a silo velgrid for the purpose at hand but it would be nice to know and maybe have the possibility in future.

**Comment by ursg** [comment]
As we haven't used vlsv2silo in years, I'm closing this request. The visit plugin works fine, and python is increasingly becoming our visualization swiss army knife anyway.
