### ISSUE TITLE
System boundary conditions

### ISSUE THREAD

**Issue by sandroos** [fmihpc/vlasiator#96]
These are rapidly becoming a mess with multiple particle populations. Currently -- if I got everything right -- one boundary condition function is set on a spatial cell (inspected from sysBoundaryFlag). Furthermore, boundary condition functions read their parameters from a single config file region, e.g., Ionosphere reads config file region "ionosphere". Proton mass and other parameters are also happily hard-coded to various shifted Maxwellian distributions and so forth.

Each particle population should have its own boundary condition functions. For example, Helium or electrons should be allowed to have different ionospheric densities than protons. I think we should re-implement the boundary condition functions to ensure that they work correctly.

**Comment by ursg** [comment]
With Vlasiator 4.0, we have now done a bunch of incompatible changes to the config file format, separating the per-population boundary parameter blocks from the population-independent ones.

A typical config will look like this:
```
[ionosphere]
centerX = 0.0
centerY = 0.0
centerZ = 0.0
geometry = 2
radius = 50.0e6
taperRadius = 100.0e6
precedence = 2

[proton_ionosphere]
rho = 1.0e6
VX0 = 0.0
VY0 = 0.0
VZ0 = 0.0
```

And can contain further ```*_ionosphere``` blocks for other species, as required.
