### ISSUE TITLE
Store fSaved as soon as any vdf is stored

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#973]
A (rare) classic: setting VDF strides properly but forgetting to activate vg_fsaved output, and analysator finds nothing out of GBs of data.

I have an inkling that actually detecting whether any VDFs would come out might be tricky, but basic non-zero checks for the strides should be enough, probably. If the strides are non zero someone put a thought and was not actively trying not to store VDFs by e.g. putting a stride bigger than the box size or something.

So (silently?) activating fsaved storage when VDFs will come out would be the nice option.

Aborting if the manual listing of the fsaved DRO is missing would be the pedantic option...

Whoever wants an easy project...

**Comment by markusbattarbee** [comment]
We do already store CellsWithBlocks into the VLSV file anyway, so another option would be to create and cache fSaved from those if it does not exist in the VDF file. 

Though that won’t help with trying to plot fSaved in VisIt - unless we add that to the plugin as well as Analysator.

**Comment by markusbattarbee** [comment]
Fixed in #976
